export * from './customer/create-customer.dto';
export * from './customer/update-customer.dto';
export * from './create-vehicle.dto';
export * from './update-vehicle.dto';
export * from './create-service.dto';
export * from './update-service.dto';
export * from './create-part.dto';
export * from './update-part.dto';
export * from './create-service-order.dto';
