apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-api
  namespace: mechanical-workshop
  labels:
    app: workshop-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workshop-api
  template:
    metadata:
      labels:
        app: workshop-api
    spec:
      automountServiceAccountToken: false
      containers:
        - name: app
          image: hashicorp/http-echo:1.0.0
          args:
            - "-listen=:3000"
            - "-text=workshop-api-ok"
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: workshop-secrets
                  key: DATABASE_URL
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
              ephemeral-storage: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
              ephemeral-storage: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20
