apiVersion: v1
kind: Secret
metadata:
  name: pet-management-secrets
<<<<<<< HEAD
type: Opaque
stringData:
  DATABASE_URL: postgres://postgres:postgres@postgres:5432/mechanical_workshop
  # Add other secrets like JWT_SECRET, API_KEYS here
  JWT_SECRET: changeme
=======
  namespace: pet-management
type: Opaque
stringData:
  JWT_SECRET: "replace_with_real_secret"
  DATABASE_PASSWORD: "password"
>>>>>>> origin/develop
