apiVersion: v1
kind: Service
metadata:
  name: workshop-api-service
  namespace: mechanical-workshop
spec:
  selector:
    app: workshop-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
