name: Billing Service CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - run: npm run test:cov

  deploy:
    if: github.event_name == 'push'
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy K8s aqui"